-- Snapshot final del estado actual (sin datos)
-- Incluye: estructura final public + RLS + funciones + triggers + indices

-- ============================================================================
-- TABLAS (PUBLIC)
-- ============================================================================

create table if not exists public.niveles (
  id bigserial primary key,
  nombre text not null
);

create table if not exists public.apoderados (
  id bigserial primary key,
  apellidos text,
  nombres text,
  dni text,
  fecha_nacimiento date,
  celular text
);

create table if not exists public.direcciones (
  id bigserial primary key,
  departamento text,
  provincia text,
  distrito text,
  domicilio text
);

create table if not exists public.aulas (
  id bigserial primary key,
  grado text not null,
  seccion text not null,
  anio integer not null,
  nivel_id bigint references public.niveles(id)
);

create table if not exists public.estudiantes (
  id bigserial primary key,
  apellidos text,
  nombres text,
  dni text,
  fecha_nacimiento date,
  sexo text,
  discapacidad text,
  apoderado_id bigint references public.apoderados(id),
  aula_id bigint references public.aulas(id),
  direccion_id bigint references public.direcciones(id),
  deleted_at timestamptz,
  created_by uuid,
  updated_by uuid,
  deleted_by uuid
);

create table if not exists public.tbl_niveleseducativos (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null unique
);

create table if not exists public.tbl_cargos (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null unique
);

create table if not exists public.tbl_especialidades (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null unique
);

create table if not exists public.tbl_escalasmagisteriales (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null unique
);

create table if not exists public.tbl_condiciones (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null unique
);

create table if not exists public.tbl_sistemaspensiones (
  id integer generated by default as identity primary key,
  nombre varchar(100) not null unique
);

create table if not exists public.tbl_personal (
  dni char(8) primary key,
  nombres varchar(100) not null,
  apellidos varchar(100) not null,
  fecha_nacimiento date,
  numero_celular varchar(15),
  codigo_modular varchar(20) not null unique,
  sistema_pensiones_id integer references public.tbl_sistemaspensiones(id),
  fecha_inicio_ejercicio_general date,
  deleted_at timestamptz,
  created_by uuid,
  updated_by uuid,
  deleted_by uuid
);

create table if not exists public.tbl_plazas (
  codigo_plaza varchar(20) primary key,
  remuneracion_bruta numeric(10,2),
  jornada_laboral integer,
  resolucion_nombramiento varchar(50),
  fecha_nombramiento_carrera date,
  fecha_ingreso_institucion date,
  nivel_educativo_id integer not null references public.tbl_niveleseducativos(id),
  cargo_id integer not null references public.tbl_cargos(id),
  especialidad_id integer references public.tbl_especialidades(id),
  escala_magisterial_id integer references public.tbl_escalasmagisteriales(id),
  condicion_id integer not null references public.tbl_condiciones(id),
  dni_personal_asignado char(8) unique references public.tbl_personal(dni)
);

create table if not exists public.user_roles (
  role varchar(50) primary key,
  description text not null
);

create table if not exists public.users_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email varchar(255) not null,
  full_name varchar(255),
  role varchar(50) default 'docente' references public.user_roles(role),
  school varchar(255),
  created_at timestamp default now(),
  updated_at timestamp default now(),
  is_active boolean not null default true
);

create unique index if not exists users_profiles_email_idx on public.users_profiles(email);

create table if not exists public.audit_log (
  id bigint generated always as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  actor_id uuid,
  actor_role varchar(50),
  school varchar(255),
  action text not null,
  entity text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb
);

-- ============================================================================
-- INDICES
-- ============================================================================

create index if not exists idx_audit_log_created_at on public.audit_log using btree (created_at desc);
create index if not exists idx_audit_log_entity on public.audit_log using btree (entity, entity_id);
create index if not exists idx_aulas_nivel_id on public.aulas using btree (nivel_id);
create index if not exists idx_estudiantes_apoderado_id on public.estudiantes using btree (apoderado_id);
create index if not exists idx_estudiantes_aula_id on public.estudiantes using btree (aula_id);
create index if not exists idx_estudiantes_deleted_at on public.estudiantes using btree (deleted_at);
create index if not exists idx_estudiantes_direccion_id on public.estudiantes using btree (direccion_id);
create index if not exists idx_tbl_personal_apellidos_nombres on public.tbl_personal using btree (apellidos, nombres);
create index if not exists idx_tbl_personal_deleted_at on public.tbl_personal using btree (deleted_at);
create index if not exists idx_tbl_personal_sistema_pensiones_id on public.tbl_personal using btree (sistema_pensiones_id);
create index if not exists idx_tbl_plazas_cargo_id on public.tbl_plazas using btree (cargo_id);
create index if not exists idx_tbl_plazas_condicion_id on public.tbl_plazas using btree (condicion_id);
create index if not exists idx_tbl_plazas_dni_personal_asignado on public.tbl_plazas using btree (dni_personal_asignado);
create index if not exists idx_tbl_plazas_escala_magisterial_id on public.tbl_plazas using btree (escala_magisterial_id);
create index if not exists idx_tbl_plazas_especialidad_id on public.tbl_plazas using btree (especialidad_id);
create index if not exists idx_tbl_plazas_nivel_educativo_id on public.tbl_plazas using btree (nivel_educativo_id);
create index if not exists idx_users_profiles_role on public.users_profiles using btree (role);

-- ============================================================================
-- FUNCIONES
-- ============================================================================

create or replace function public.current_user_role()
returns character varying
language sql
stable security definer
set search_path = 'public'
as $function$
  select coalesce(up.role, 'consulta')::varchar
  from public.users_profiles up
  where up.id = auth.uid()
  limit 1;
$function$;

create or replace function public.current_user_school()
returns character varying
language sql
stable security definer
set search_path = 'public'
as $function$
  select up.school
  from public.users_profiles up
  where up.id = auth.uid()
  limit 1;
$function$;

create or replace function public.has_any_role(roles text[])
returns boolean
language sql
stable
set search_path = 'public'
as $function$
  select (public.current_user_role())::text = any(roles);
$function$;

create or replace function public.can_manage_school_data()
returns boolean
language sql
stable
set search_path = 'public'
as $function$
  select public.has_any_role(array['admin','direccion','secretaria']);
$function$;

create or replace function public.can_read_school_data()
returns boolean
language sql
stable
set search_path = 'public'
as $function$
  select public.has_any_role(array['admin','direccion','secretaria','docente','consulta']);
$function$;

create or replace function public.write_audit_log(p_action text, p_entity text, p_entity_id text, p_details jsonb default '{}'::jsonb)
returns void
language plpgsql
security definer
set search_path = 'public'
as $function$
begin
  insert into public.audit_log(actor_id, actor_role, school, action, entity, entity_id, details)
  values (
    auth.uid(),
    public.current_user_role(),
    public.current_user_school(),
    p_action,
    p_entity,
    p_entity_id,
    coalesce(p_details, '{}'::jsonb)
  );
end;
$function$;

create or replace function public.create_student_full(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = 'public'
as $function$
declare
  v_student jsonb := p_payload;
  v_dir jsonb := coalesce(p_payload->'direccion', '{}'::jsonb);
  v_guard jsonb := coalesce(p_payload->'apoderado', '{}'::jsonb);
  v_nombres text := btrim(coalesce(v_student->>'nombres',''));
  v_apellidos text := btrim(coalesce(v_student->>'apellidos',''));
  v_dni text := btrim(coalesce(v_student->>'dni',''));
  v_sexo text := btrim(coalesce(v_student->>'sexo',''));
  v_fecha_nac date;
  v_direccion_id bigint;
  v_apoderado_id bigint;
  v_aula_id bigint;
  v_student_id bigint;
begin
  if not public.can_manage_school_data() then
    raise exception 'No autorizado';
  end if;

  if v_nombres = '' or v_apellidos = '' or v_dni = '' or v_sexo = '' then
    raise exception 'Campos obligatorios: nombres, apellidos, dni, sexo';
  end if;

  if v_dni !~ '^\d{8}$' then
    raise exception 'DNI invalido';
  end if;

  if coalesce(v_student->>'fecha_nacimiento','') <> '' then
    v_fecha_nac := (v_student->>'fecha_nacimiento')::date;
    if v_fecha_nac > current_date then
      raise exception 'Fecha de nacimiento no puede ser futura';
    end if;
  end if;

  if coalesce(v_dir->>'departamento','') <> ''
    or coalesce(v_dir->>'provincia','') <> ''
    or coalesce(v_dir->>'distrito','') <> ''
    or coalesce(v_dir->>'domicilio','') <> '' then
    insert into public.direcciones(departamento, provincia, distrito, domicilio)
    values (
      nullif(btrim(v_dir->>'departamento'), ''),
      nullif(btrim(v_dir->>'provincia'), ''),
      nullif(btrim(v_dir->>'distrito'), ''),
      nullif(btrim(v_dir->>'domicilio'), '')
    )
    returning id into v_direccion_id;
  end if;

  if coalesce(v_guard->>'nombres','') <> '' or coalesce(v_guard->>'apellidos','') <> '' then
    if coalesce(v_guard->>'dni','') <> '' and (v_guard->>'dni') !~ '^\d{8}$' then
      raise exception 'DNI del apoderado invalido';
    end if;

    insert into public.apoderados(nombres, apellidos, dni, fecha_nacimiento, celular)
    values (
      nullif(btrim(v_guard->>'nombres'), ''),
      nullif(btrim(v_guard->>'apellidos'), ''),
      nullif(btrim(v_guard->>'dni'), ''),
      nullif(v_guard->>'fecha_nacimiento', '')::date,
      nullif(btrim(v_guard->>'celular'), '')
    )
    returning id into v_apoderado_id;
  end if;

  if coalesce(v_student->>'aula_id','') <> '' then
    v_aula_id := (v_student->>'aula_id')::bigint;
  elsif coalesce(v_student->>'grado','') <> '' and coalesce(v_student->>'seccion','') <> '' then
    select id into v_aula_id
    from public.aulas
    where grado = (v_student->>'grado')
      and seccion = (v_student->>'seccion')
    limit 1;

    if v_aula_id is null then
      raise exception 'Combinacion de grado y seccion no valida';
    end if;
  end if;

  insert into public.estudiantes(
    nombres,
    apellidos,
    dni,
    fecha_nacimiento,
    sexo,
    discapacidad,
    aula_id,
    apoderado_id,
    direccion_id,
    created_by,
    updated_by,
    deleted_at
  ) values (
    v_nombres,
    v_apellidos,
    v_dni,
    v_fecha_nac,
    v_sexo,
    nullif(btrim(v_student->>'discapacidad'), ''),
    v_aula_id,
    v_apoderado_id,
    v_direccion_id,
    auth.uid(),
    auth.uid(),
    null
  )
  returning id into v_student_id;

  perform public.write_audit_log('create', 'estudiantes', v_student_id::text, jsonb_build_object('dni', v_dni));

  return jsonb_build_object('student_id', v_student_id);
end;
$function$;

create or replace function public.soft_delete_student(p_student_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = 'public'
as $function$
declare
  v_exists bigint;
begin
  if not public.can_manage_school_data() then
    raise exception 'No autorizado';
  end if;

  select id into v_exists
  from public.estudiantes
  where id = p_student_id and deleted_at is null;

  if v_exists is null then
    raise exception 'Estudiante no encontrado';
  end if;

  update public.estudiantes
  set deleted_at = timezone('utc', now()),
      deleted_by = auth.uid(),
      updated_by = auth.uid()
  where id = p_student_id;

  perform public.write_audit_log('soft_delete', 'estudiantes', p_student_id::text, '{}'::jsonb);

  return jsonb_build_object('success', true);
end;
$function$;

create or replace function public.create_personal_full(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = 'public'
as $function$
declare
  v_dni text := btrim(coalesce(p_payload->>'dni',''));
  v_nombres text := btrim(coalesce(p_payload->>'nombres',''));
  v_apellidos text := btrim(coalesce(p_payload->>'apellidos',''));
  v_codigo_modular text := btrim(coalesce(p_payload->>'codigo_modular',''));
  v_fecha_nac date;
  v_personal_dni char(8);
  v_plaza jsonb := coalesce(p_payload->'plaza', '{}'::jsonb);
begin
  if not public.can_manage_school_data() then
    raise exception 'No autorizado';
  end if;

  if v_dni = '' or v_nombres = '' or v_apellidos = '' or v_codigo_modular = '' then
    raise exception 'Campos obligatorios: nombres, apellidos, dni, codigo_modular';
  end if;

  if v_dni !~ '^\d{8}$' then
    raise exception 'DNI invalido';
  end if;

  if v_codigo_modular !~ '^[A-Za-z0-9-]{4,20}$' then
    raise exception 'Codigo modular invalido';
  end if;

  if coalesce(p_payload->>'fecha_nacimiento','') <> '' then
    v_fecha_nac := (p_payload->>'fecha_nacimiento')::date;
    if v_fecha_nac > current_date then
      raise exception 'Fecha de nacimiento no puede ser futura';
    end if;
  end if;

  insert into public.tbl_personal(
    dni,
    nombres,
    apellidos,
    fecha_nacimiento,
    numero_celular,
    codigo_modular,
    sistema_pensiones_id,
    fecha_inicio_ejercicio_general,
    created_by,
    updated_by,
    deleted_at
  ) values (
    v_dni,
    v_nombres,
    v_apellidos,
    v_fecha_nac,
    nullif(btrim(p_payload->>'numero_celular'), ''),
    v_codigo_modular,
    nullif(p_payload->>'sistema_pensiones_id','')::int,
    nullif(p_payload->>'fecha_inicio_ejercicio_general','')::date,
    auth.uid(),
    auth.uid(),
    null
  ) returning dni into v_personal_dni;

  if coalesce(v_plaza->>'codigo_plaza','') <> '' or coalesce(v_plaza->>'cargo_id','') <> '' then
    insert into public.tbl_plazas(
      codigo_plaza,
      dni_personal_asignado,
      cargo_id,
      especialidad_id,
      nivel_educativo_id,
      escala_magisterial_id,
      condicion_id,
      resolucion_nombramiento,
      fecha_nombramiento_carrera,
      fecha_ingreso_institucion,
      jornada_laboral,
      remuneracion_bruta
    ) values (
      coalesce(nullif(v_plaza->>'codigo_plaza',''), concat('PLAZA-', extract(epoch from now())::bigint::text)),
      v_personal_dni,
      nullif(v_plaza->>'cargo_id','')::int,
      nullif(v_plaza->>'especialidad_id','')::int,
      nullif(v_plaza->>'nivel_educativo_id','')::int,
      nullif(v_plaza->>'escala_magisterial_id','')::int,
      nullif(v_plaza->>'condicion_id','')::int,
      nullif(v_plaza->>'resolucion_nombramiento',''),
      nullif(v_plaza->>'fecha_nombramiento_carrera','')::date,
      nullif(v_plaza->>'fecha_ingreso_institucion','')::date,
      nullif(v_plaza->>'jornada_laboral','')::int,
      nullif(v_plaza->>'remuneracion_bruta','')::numeric
    );
  end if;

  perform public.write_audit_log('create', 'tbl_personal', v_personal_dni::text, jsonb_build_object('dni', v_personal_dni::text));

  return jsonb_build_object('dni', v_personal_dni::text);
end;
$function$;

create or replace function public.soft_delete_personal(p_dni text)
returns jsonb
language plpgsql
security definer
set search_path = 'public'
as $function$
declare
  v_dni char(8) := btrim(coalesce(p_dni,''));
begin
  if not public.can_manage_school_data() then
    raise exception 'No autorizado';
  end if;

  update public.tbl_plazas
  set dni_personal_asignado = null
  where dni_personal_asignado = v_dni;

  update public.tbl_personal
  set deleted_at = timezone('utc', now()),
      deleted_by = auth.uid(),
      updated_by = auth.uid()
  where dni = v_dni and deleted_at is null;

  if not found then
    raise exception 'Personal no encontrado';
  end if;

  perform public.write_audit_log('soft_delete', 'tbl_personal', v_dni::text, '{}'::jsonb);

  return jsonb_build_object('success', true);
end;
$function$;

create or replace function public.get_personal_with_relations(p_offset integer default 0, p_limit integer default 24)
returns setof json
language sql
stable security definer
set search_path to 'public'
as $function$
select json_build_object(
  'dni', p.dni,
  'nombres', p.nombres,
  'apellidos', p.apellidos,
  'fecha_nacimiento', p.fecha_nacimiento,
  'numero_celular', p.numero_celular,
  'codigo_modular', p.codigo_modular,
  'sistema_pensiones_id', p.sistema_pensiones_id,
  'fecha_inicio_ejercicio_general', p.fecha_inicio_ejercicio_general,
  'sistema_pensiones', case
    when sp.id is not null then json_build_object('id', sp.id, 'nombre', sp.nombre)
    else null
  end,
  'plaza', case
    when pl.codigo_plaza is not null then json_build_object(
      'codigo_plaza', pl.codigo_plaza,
      'remuneracion_bruta', pl.remuneracion_bruta,
      'jornada_laboral', pl.jornada_laboral,
      'resolucion_nombramiento', pl.resolucion_nombramiento,
      'fecha_nombramiento_carrera', pl.fecha_nombramiento_carrera,
      'fecha_ingreso_institucion', pl.fecha_ingreso_institucion,
      'nivel_educativo', case
        when ne.id is not null then json_build_object('id', ne.id, 'nombre', ne.nombre)
        else null
      end,
      'cargo', case
        when c.id is not null then json_build_object('id', c.id, 'nombre', c.nombre)
        else null
      end,
      'especialidad', case
        when e.id is not null then json_build_object('id', e.id, 'nombre', e.nombre)
        else null
      end,
      'escala_magisterial', case
        when em.id is not null then json_build_object('id', em.id, 'nombre', em.nombre)
        else null
      end,
      'condicion', case
        when cond.id is not null then json_build_object('id', cond.id, 'nombre', cond.nombre)
        else null
      end
    )
    else null
  end
)
from tbl_personal p
left join tbl_sistemaspensiones sp on p.sistema_pensiones_id = sp.id
left join tbl_plazas pl on p.dni = pl.dni_personal_asignado
left join tbl_niveleseducativos ne on pl.nivel_educativo_id = ne.id
left join tbl_cargos c on pl.cargo_id = c.id
left join tbl_especialidades e on pl.especialidad_id = e.id
left join tbl_escalasmagisteriales em on pl.escala_magisterial_id = em.id
left join tbl_condiciones cond on pl.condicion_id = cond.id
order by
  case when ne.id = 3 then 1
       when ne.id = 2 then 2
       when ne.id = 1 then 3
       else 999 end asc,
  coalesce(c.id, 999) asc,
  p.apellidos asc,
  p.nombres asc
offset p_offset
limit p_limit
$function$;

create or replace function public.search_personal_with_filters(p_search text default ''::text, p_cargo_id integer default null::integer, p_especialidad_id integer default null::integer, p_nivel_id integer default null::integer, p_offset integer default 0, p_limit integer default 24)
returns setof json
language sql
stable security definer
set search_path to 'public'
as $function$
select json_build_object(
  'dni', p.dni,
  'nombres', p.nombres,
  'apellidos', p.apellidos,
  'fecha_nacimiento', p.fecha_nacimiento,
  'numero_celular', p.numero_celular,
  'codigo_modular', p.codigo_modular,
  'sistema_pensiones_id', p.sistema_pensiones_id,
  'fecha_inicio_ejercicio_general', p.fecha_inicio_ejercicio_general,
  'sistema_pensiones', case
    when sp.id is not null then json_build_object('id', sp.id, 'nombre', sp.nombre)
    else null
  end,
  'plaza', case
    when pl.codigo_plaza is not null then json_build_object(
      'codigo_plaza', pl.codigo_plaza,
      'remuneracion_bruta', pl.remuneracion_bruta,
      'jornada_laboral', pl.jornada_laboral,
      'resolucion_nombramiento', pl.resolucion_nombramiento,
      'fecha_nombramiento_carrera', pl.fecha_nombramiento_carrera,
      'fecha_ingreso_institucion', pl.fecha_ingreso_institucion,
      'nivel_educativo', case
        when ne.id is not null then json_build_object('id', ne.id, 'nombre', ne.nombre)
        else null
      end,
      'cargo', case
        when c.id is not null then json_build_object('id', c.id, 'nombre', c.nombre)
        else null
      end,
      'especialidad', case
        when e.id is not null then json_build_object('id', e.id, 'nombre', e.nombre)
        else null
      end,
      'escala_magisterial', case
        when em.id is not null then json_build_object('id', em.id, 'nombre', em.nombre)
        else null
      end,
      'condicion', case
        when cond.id is not null then json_build_object('id', cond.id, 'nombre', cond.nombre)
        else null
      end
    )
    else null
  end
)
from tbl_personal p
left join tbl_sistemaspensiones sp on p.sistema_pensiones_id = sp.id
left join tbl_plazas pl on p.dni = pl.dni_personal_asignado
left join tbl_niveleseducativos ne on pl.nivel_educativo_id = ne.id
left join tbl_cargos c on pl.cargo_id = c.id
left join tbl_especialidades e on pl.especialidad_id = e.id
left join tbl_escalasmagisteriales em on pl.escala_magisterial_id = em.id
left join tbl_condiciones cond on pl.condicion_id = cond.id
where
  (p_search = ''
   or p.nombres ilike '%' || p_search || '%'
   or p.apellidos ilike '%' || p_search || '%'
   or p.dni ilike '%' || p_search || '%'
   or p.codigo_modular ilike '%' || p_search || '%')
  and (p_cargo_id is null or c.id = p_cargo_id)
  and (p_especialidad_id is null or e.id = p_especialidad_id)
  and (p_nivel_id is null or ne.id = p_nivel_id)
order by
  case when ne.id = 3 then 1
       when ne.id = 2 then 2
       when ne.id = 1 then 3
       else 999 end asc,
  coalesce(c.id, 999) asc,
  p.apellidos asc,
  p.nombres asc
offset p_offset
limit p_limit
$function$;

create or replace function public.get_user_role(user_id uuid)
returns text
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  user_role text;
begin
  select role into user_role from public.users_profiles where id = user_id limit 1;
  return coalesce(user_role, 'admin');
end;
$function$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  insert into public.users_profiles (id, email, full_name, role)
  values (
    NEW.id,
    NEW.email,
    coalesce(NEW.raw_user_meta_data->>'full_name', NEW.email),
    coalesce(NEW.raw_user_meta_data->>'role', 'admin')
  );
  return NEW;
end;
$function$;

create or replace function public.set_user_admin_role()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  update auth.users
  set raw_app_meta_data = jsonb_set(
    coalesce(raw_app_meta_data, '{}'),
    '{role}',
    '"admin"'
  )
  where id = NEW.id;

  return NEW;
end;
$function$;

-- Advertencia: esta funcion inserta en public.role_change_audit.
-- La tabla fue eliminada por migracion 20251117141005.
create or replace function public.audit_role_change()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
BEGIN
  IF OLD.role IS DISTINCT FROM NEW.role THEN
    INSERT INTO public.role_change_audit (user_id, old_role, new_role)
    VALUES (NEW.id, OLD.role, NEW.role);
  END IF;
  RETURN NEW;
END;
$function$;

-- ============================================================================
-- TRIGGERS
-- ============================================================================

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop trigger if exists audit_role_change_trigger on public.users_profiles;
create trigger audit_role_change_trigger
before update on public.users_profiles
for each row execute function public.audit_role_change();

drop trigger if exists set_user_admin_role_trigger on public.users_profiles;
create trigger set_user_admin_role_trigger
after insert on public.users_profiles
for each row execute function public.set_user_admin_role();

-- ============================================================================
-- RLS Y POLITICAS
-- ============================================================================

alter table public.users_profiles enable row level security;
alter table public.niveles enable row level security;
alter table public.aulas enable row level security;
alter table public.apoderados enable row level security;
alter table public.direcciones enable row level security;
alter table public.estudiantes enable row level security;
alter table public.tbl_niveleseducativos enable row level security;
alter table public.tbl_cargos enable row level security;
alter table public.tbl_especialidades enable row level security;
alter table public.tbl_escalasmagisteriales enable row level security;
alter table public.tbl_condiciones enable row level security;
alter table public.tbl_sistemaspensiones enable row level security;
alter table public.tbl_personal enable row level security;
alter table public.tbl_plazas enable row level security;
alter table public.audit_log enable row level security;
alter table public.user_roles enable row level security;

DO $$
DECLARE
  rec record;
BEGIN
  FOR rec IN
    SELECT tablename, policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename IN (
        'users_profiles','niveles','aulas','apoderados','direcciones','estudiantes',
        'tbl_niveleseducativos','tbl_cargos','tbl_especialidades','tbl_escalasmagisteriales',
        'tbl_condiciones','tbl_sistemaspensiones','tbl_personal','tbl_plazas','audit_log',
        'user_roles'
      )
  LOOP
    EXECUTE format('drop policy if exists %I on public.%I', rec.policyname, rec.tablename);
  END LOOP;
END $$;

create policy p_apoderados_delete on public.apoderados for delete to authenticated using (can_manage_school_data());
create policy p_apoderados_insert on public.apoderados for insert to authenticated with check (can_manage_school_data());
create policy p_apoderados_select on public.apoderados for select to authenticated using (can_read_school_data());
create policy p_apoderados_update on public.apoderados for update to authenticated using (can_manage_school_data()) with check (can_manage_school_data());

create policy p_audit_log_insert on public.audit_log for insert to authenticated with check (has_any_role(array['admin'::text, 'direccion'::text, 'secretaria'::text]));
create policy p_audit_log_select on public.audit_log for select to authenticated using (has_any_role(array['admin'::text, 'direccion'::text]));

create policy p_aulas_select on public.aulas for select to authenticated using (can_read_school_data());

create policy p_direcciones_delete on public.direcciones for delete to authenticated using (can_manage_school_data());
create policy p_direcciones_insert on public.direcciones for insert to authenticated with check (can_manage_school_data());
create policy p_direcciones_select on public.direcciones for select to authenticated using (can_read_school_data());
create policy p_direcciones_update on public.direcciones for update to authenticated using (can_manage_school_data()) with check (can_manage_school_data());

create policy p_estudiantes_delete on public.estudiantes for delete to authenticated using (can_manage_school_data());
create policy p_estudiantes_insert on public.estudiantes for insert to authenticated with check (can_manage_school_data());
create policy p_estudiantes_select on public.estudiantes for select to authenticated using (can_read_school_data() and (deleted_at is null));
create policy p_estudiantes_update on public.estudiantes for update to authenticated using (can_manage_school_data()) with check (can_manage_school_data());

create policy p_niveles_select on public.niveles for select to authenticated using (can_read_school_data());

create policy p_tbl_cargos_delete on public.tbl_cargos for delete to authenticated using (has_any_role(array['admin'::text]));
create policy p_tbl_cargos_insert on public.tbl_cargos for insert to authenticated with check (has_any_role(array['admin'::text]));
create policy p_tbl_cargos_select on public.tbl_cargos for select to authenticated using (can_read_school_data());
create policy p_tbl_cargos_update on public.tbl_cargos for update to authenticated using (has_any_role(array['admin'::text])) with check (has_any_role(array['admin'::text]));

create policy p_tbl_condiciones_delete on public.tbl_condiciones for delete to authenticated using (has_any_role(array['admin'::text]));
create policy p_tbl_condiciones_insert on public.tbl_condiciones for insert to authenticated with check (has_any_role(array['admin'::text]));
create policy p_tbl_condiciones_select on public.tbl_condiciones for select to authenticated using (can_read_school_data());
create policy p_tbl_condiciones_update on public.tbl_condiciones for update to authenticated using (has_any_role(array['admin'::text])) with check (has_any_role(array['admin'::text]));

create policy p_tbl_escalasmagisteriales_delete on public.tbl_escalasmagisteriales for delete to authenticated using (has_any_role(array['admin'::text]));
create policy p_tbl_escalasmagisteriales_insert on public.tbl_escalasmagisteriales for insert to authenticated with check (has_any_role(array['admin'::text]));
create policy p_tbl_escalasmagisteriales_select on public.tbl_escalasmagisteriales for select to authenticated using (can_read_school_data());
create policy p_tbl_escalasmagisteriales_update on public.tbl_escalasmagisteriales for update to authenticated using (has_any_role(array['admin'::text])) with check (has_any_role(array['admin'::text]));

create policy p_tbl_especialidades_delete on public.tbl_especialidades for delete to authenticated using (has_any_role(array['admin'::text]));
create policy p_tbl_especialidades_insert on public.tbl_especialidades for insert to authenticated with check (has_any_role(array['admin'::text]));
create policy p_tbl_especialidades_select on public.tbl_especialidades for select to authenticated using (can_read_school_data());
create policy p_tbl_especialidades_update on public.tbl_especialidades for update to authenticated using (has_any_role(array['admin'::text])) with check (has_any_role(array['admin'::text]));

create policy p_tbl_niveleseducativos_delete on public.tbl_niveleseducativos for delete to authenticated using (has_any_role(array['admin'::text]));
create policy p_tbl_niveleseducativos_insert on public.tbl_niveleseducativos for insert to authenticated with check (has_any_role(array['admin'::text]));
create policy p_tbl_niveleseducativos_select on public.tbl_niveleseducativos for select to authenticated using (can_read_school_data());
create policy p_tbl_niveleseducativos_update on public.tbl_niveleseducativos for update to authenticated using (has_any_role(array['admin'::text])) with check (has_any_role(array['admin'::text]));

create policy p_tbl_personal_delete on public.tbl_personal for delete to authenticated using (can_manage_school_data());
create policy p_tbl_personal_insert on public.tbl_personal for insert to authenticated with check (can_manage_school_data());
create policy p_tbl_personal_select on public.tbl_personal for select to authenticated using (can_read_school_data() and (deleted_at is null));
create policy p_tbl_personal_update on public.tbl_personal for update to authenticated using (can_manage_school_data()) with check (can_manage_school_data());

create policy p_tbl_plazas_delete on public.tbl_plazas for delete to authenticated using (can_manage_school_data());
create policy p_tbl_plazas_insert on public.tbl_plazas for insert to authenticated with check (can_manage_school_data());
create policy p_tbl_plazas_select on public.tbl_plazas for select to authenticated using (can_read_school_data());
create policy p_tbl_plazas_update on public.tbl_plazas for update to authenticated using (can_manage_school_data()) with check (can_manage_school_data());

create policy p_tbl_sistemaspensiones_delete on public.tbl_sistemaspensiones for delete to authenticated using (has_any_role(array['admin'::text]));
create policy p_tbl_sistemaspensiones_insert on public.tbl_sistemaspensiones for insert to authenticated with check (has_any_role(array['admin'::text]));
create policy p_tbl_sistemaspensiones_select on public.tbl_sistemaspensiones for select to authenticated using (can_read_school_data());
create policy p_tbl_sistemaspensiones_update on public.tbl_sistemaspensiones for update to authenticated using (has_any_role(array['admin'::text])) with check (has_any_role(array['admin'::text]));

create policy p_user_roles_delete on public.user_roles for delete to authenticated using (has_any_role(array['admin'::text]));
create policy p_user_roles_insert on public.user_roles for insert to authenticated with check (has_any_role(array['admin'::text]));
create policy p_user_roles_select on public.user_roles for select to authenticated using (can_read_school_data());
create policy p_user_roles_update on public.user_roles for update to authenticated using (has_any_role(array['admin'::text])) with check (has_any_role(array['admin'::text]));

create policy p_users_profiles_delete on public.users_profiles for delete to authenticated using (has_any_role(array['admin'::text]));
create policy p_users_profiles_insert on public.users_profiles for insert to authenticated with check (((id = (select auth.uid() as uid)) or has_any_role(array['admin'::text])));
create policy p_users_profiles_select on public.users_profiles for select to authenticated using (((id = (select auth.uid() as uid)) or has_any_role(array['admin'::text, 'direccion'::text])));
create policy p_users_profiles_update on public.users_profiles for update to authenticated using (((id = (select auth.uid() as uid)) or has_any_role(array['admin'::text]))) with check (((id = (select auth.uid() as uid)) or has_any_role(array['admin'::text])));

-- ============================================================================
-- GRANTS EXPLICITOS (ademas de los defaults)
-- ============================================================================

grant execute on function public.write_audit_log(text, text, text, jsonb) to authenticated;
grant execute on function public.create_student_full(jsonb) to authenticated;
grant execute on function public.soft_delete_student(bigint) to authenticated;
grant execute on function public.create_personal_full(jsonb) to authenticated;
grant execute on function public.soft_delete_personal(text) to authenticated;
